# 参考 `application-example.yaml` 并在处添加订阅规则，请注意缩进
# Refer to `application-example.yaml` and add subscription rules there，please note the indentation
application:

  input:

    - name: AdGuard 移动广告过滤器
      path: https://filters.adtidy.org/extension/ublock/filters/11_optimized.txt
      type: easylist

    - name: AdGuard 防跟踪保护过滤器
      path: https://filters.adtidy.org/extension/ublock/filters/3_optimized.txt
      type: easylist

    - name: AdGuard URL跟踪过滤器
      path: https://filters.adtidy.org/extension/ublock/filters/17_optimized.txt
      type: easylist

    - name: AdGuard 恼人广告过滤器
      path: https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt
      type: easylist

    - name: AdGuard 解除搜索广告和自我推销过滤器
      path: https://filters.adtidy.org/extension/ublock/filters/10_optimized.txt
      type: easylist

    - name: AdGuard 中文过滤器
      path: https://filters.adtidy.org/extension/ublock/filters/224_optimized.txt
      type: easylist

    - name: AWAvenue-Adblock-Rule
      path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
      type: easylist

    - name: NoAppDownload
      path: https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt
      type: easylist

    - name: xndeye web-ad-rule
      path: https://raw.githubusercontent.com/xndeye/web-ad-rule/master/easylist.txt
      type: easylist

    - name: xinggsf movie
      path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt

    - name: cjxlist annoyance
      path: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

    - name: EasyList China+EasyList
      path: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt

    - name: ABP filters
      path: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

    - name: uBlockOrigin privacy
      path: https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/privacy.txt

    - name: Telemetry Lists - Aggregated
      path: https://raw.githubusercontent.com/SystemJargon/filters/refs/heads/main/telemetry.txt

    - name: GoodbyeAds-Xiaomi
      path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Xiaomi-Extension.txt

    - name: GoodbyeAds-Huawei
      path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Huawei-AdBlock.txt

    - name: GoodbyeAds-Samsung
      path: https://cdn.jsdelivr.net/gh/jerryn70/GoodbyeAds@master/Extension/GoodbyeAds-Samsung-AdBlock.txt

    # ========== NEW ADDITIONS START HERE ==========

    - name: Hagezi Multi Pro - Adblock
      path: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
      type: easylist

    - name: Hagezi Threat Intelligence Feeds
      path: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.txt
      type: easylist

    - name: OISD Big - Adblock
      path: https://big.oisd.nl
      type: easylist

    - name: 1Hosts Pro - Adblock
      path: https://o0.pages.dev/Pro/adblock.txt
      type: easylist

    - name: EasyPrivacy
      path: https://easylist.to/easylist/easyprivacy.txt
      type: easylist

    - name: Fanboy Annoyance List
      path: https://secure.fanboy.co.nz/fanboy-annoyance.txt
      type: easylist

    - name: Peter Lowe Ad Server List
      path: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=0&mimetype=plaintext
      type: easylist

    - name: Steven Black Hosts
      path: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      type: hosts

    - name: Hagezi Multi Pro - DNSMasq
      path: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/pro.txt
      type: dnsmasq

    - name: Hagezi Multi Pro - Hosts
      path: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/pro.txt
      type: hosts

    - name: 1Hosts Pro - Hosts
      path: https://o0.pages.dev/Pro/hosts.txt
      type: hosts

    - name: uBlock Origin Unbreak
      path: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
      type: easylist

    # ========== NEW ADDITIONS END HERE ==========

    - name: 'xndeye private adblock list'
      path: 'rule/private.txt'
      type: easylist

  output:
    file_header: |
      Title: xndeye adblock list of ${type}
      Total Size: ${total}
      Last Modified: ${date}
      Homepage: https://github.com/WY-WY-W/adblock_list

    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        file_header: |
          Title: xndeye adblock list of dns
          Total Size: ${total}
          Last Modified: ${date}
          Homepage: https://github.com/WY-WY-W/adblock_list
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts

  config:

    expected_quantity: 2000000
    fault_tolerance: 0.0001

    domain-detect:
      enable: true
      timeout: 3000
      concurrency: 128
      provider:
        - 1.1.1.1
        - 8.8.8.8
